version: '3'
services:
  rdrive:
    image: rclone/rclone
    restart: always
    volumes:
      - $MOUNTPOINT_CONFIG:/rclone
      - $MOUNTPOINT_CONFIG/config:/config/rclone
      - $MOUNTPOINT:/data:shared
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    entrypoint: /rclone/init_rclone.sh
